export const adminLabels = {
  checkingSession: "جاري التحقق من الجلسة...",
  dashboardTitle: "لوحة التحكم",
  dashboardSubtitle: "إدارة Organic Store",
  viewSite: "عرض الموقع",
  viewSiteShort: "الموقع",
  logout: "تسجيل الخروج",
  dashboardSection: "قسم لوحة التحكم",
  save: "حفظ",
  saving: "جاري الحفظ...",
  cancel: "إلغاء",
  close: "إغلاق",
  refresh: "تحديث",
  edit: "تعديل",
  delete: "حذف",
  visible: "ظاهر",
  hidden: "مخفي",
  active: "نشط",
  yes: "نعم",
  no: "لا",
  loading: "جاري التحميل...",
  all: "الكل",
  view: "عرض",
  viewDetails: "عرض التفاصيل",
  customer: "العميل",
  phone: "الهاتف",
  address: "العنوان",
  notes: "ملاحظات",
  items: "العناصر",
  total: "الإجمالي",
  date: "التاريخ",
  status: "الحالة",
  updateStatus: "تحديث الحالة",
  whatsappSent: "تم إرسال واتساب:",
  moveUp: "تحريك لأعلى",
  moveDown: "تحريك لأسفل",
  changeImage: "تغيير الصورة",
  closeImagePicker: "إغلاق محدد الصور",
  preview: "معاينة",
  emoji: "رمز تعبيري",
  price: "السعر",
  category: "الفئة",
  unit: "الوحدة",
  type: "النوع",
  sortOrder: "ترتيب العرض",
  published: "منشور",
  offer: "عرض",
  noProduct: "بدون منتج",
  linkedProduct: "المنتج المرتبط",
  tabs: {
    orders: "الطلبات",
    products: "المنتجات",
    offers: "العروض الحالية",
    partnerships: "طلبات التعاقد",
    slider: "سلايدر الرئيسية",
    about: "صفحة من نحن",
    blog: "المدونة",
    settings: "إعدادات الموقع",
  },
  orderStatus: {
    pending: "قيد الانتظار",
    confirmed: "مؤكد",
    delivered: "تم التسليم",
    cancelled: "ملغي",
  },
  partnershipStatus: {
    new: "جديد",
    reviewed: "تمت المراجعة",
    contacted: "تم التواصل",
    closed: "مغلق",
  },
  login: {
    title: "لوحة التحكم",
    subtitle: "إدارة Organic Store",
    password: "كلمة مرور المسؤول",
    passwordPlaceholder: "أدخل كلمة المرور",
    signIn: "تسجيل الدخول",
    signingIn: "جاري تسجيل الدخول...",
    error: "كلمة المرور غير صحيحة.",
  },
  fields: {
    nameArabic: "الاسم (عربي)",
    nameEnglish: "الاسم (إنجليزي)",
    descriptionArabic: "الوصف (عربي)",
    descriptionEnglish: "الوصف (إنجليزي)",
    titleArabic: "العنوان (عربي)",
    titleEnglish: "العنوان (إنجليزي)",
    badgeArabic: "الشارة (عربي)",
    badgeEnglish: "الشارة (إنجليزي)",
    labelArabic: "التسمية (عربي)",
    labelEnglish: "التسمية (إنجليزي)",
    pageTitleArabic: "عنوان الصفحة (عربي)",
    pageTitleEnglish: "عنوان الصفحة (إنجليزي)",
    pageDescriptionArabic: "وصف الصفحة (عربي)",
    pageDescriptionEnglish: "وصف الصفحة (إنجليزي)",
    excerptArabic: "المقتطف (عربي)",
    excerptEnglish: "المقتطف (إنجليزي)",
    contentArabic: "المحتوى (عربي)",
    contentEnglish: "المحتوى (إنجليزي)",
    slug: "المعرّف (رابط URL)",
    readTimeMinutes: "وقت القراءة (دقائق)",
    defaultQuantityGrams: "الكمية الافتراضية (جرام)",
  },
  orders: {
    title: "الطلبات",
    loadError: "فشل تحميل الطلبات",
    loadErrorDetail:
      "تعذّر تحميل الطلبات: {error}. الطلبات مخزّنة محلياً في هذا المشروع حتى يتم إعداد Supabase.",
    loading: "جاري تحميل الطلبات...",
    noOrders: "لا توجد طلبات بعد",
    orderDetails: "تفاصيل الطلب",
    statsTotal: "الإجمالي",
    statsPending: "قيد الانتظار",
    statsConfirmed: "مؤكد",
    statsDelivered: "تم التسليم",
  },
  products: {
    title: "المنتجات",
    countShown: "{shown} من {total} منتج معروض",
    addProduct: "+ إضافة منتج",
    editProduct: "تعديل المنتج",
    saveProduct: "حفظ المنتج",
    searchPlaceholder: "بحث بالاسم العربي/الإنجليزي أو المعرّف أو الفئة...",
    allCategories: "جميع الفئات",
    loading: "جاري تحميل المنتجات...",
    noProducts: "لم يُعثر على منتجات",
    noProductsHint: "جرّب مصطلح بحث أو فئة مختلفة.",
    deleteConfirm: "هل تريد حذف هذا المنتج؟",
    errorSaving: "حدث خطأ أثناء حفظ المنتج",
    created: "تم إنشاء المنتج!",
    saved: "تم حفظ المنتج!",
    deleted: "تم حذف المنتج",
    customPricing: "سعر مخصص",
    comingSoon: "قريباً",
    visibleOnWebsite: "المنتج ظاهر على الموقع",
  },
  offers: {
    title: "العروض الحالية",
    subtitle: "إدارة العرضين المعروضين في تبويب العروض الحالية بالمتجر.",
    saveOffers: "حفظ العروض",
    loading: "جاري تحميل العروض...",
    errorSaving: "حدث خطأ أثناء حفظ العروض",
    saved: "تم حفظ العروض!",
    offerNumber: "عرض {n}",
    offerImage: "صورة العرض",
  },
  slider: {
    title: "سلايدر الصفحة الرئيسية",
    subtitle: "تحكم في صور السلايدر وترتيبها على الصفحة الرئيسية.",
    addSlide: "+ إضافة شريحة",
    saveSlider: "حفظ السلايدر",
    loading: "جاري تحميل السلايدر...",
    noSlides: "لا توجد شرائح بعد",
    addFirstSlide: "إضافة أول شريحة",
    deleteConfirm: "هل تريد حذف هذه الشريحة؟",
    errorSaving: "حدث خطأ أثناء حفظ السلايدر",
    saved: "تم حفظ السلايدر!",
    sliderImage: "صورة الشريحة",
    newSlide: "شريحة جديدة",
  },
  about: {
    title: "صفحة من نحن",
    subtitle: "عدّل كل عنصر في صفحة من نحن بالعربية والإنجليزية.",
    previewPage: "معاينة الصفحة",
    saveAbout: "حفظ صفحة من نحن",
    loading: "جاري تحميل صفحة من نحن...",
    loadFailed: "فشل تحميل صفحة من نحن.",
    errorSaving: "حدث خطأ أثناء حفظ صفحة من نحن",
    saved: "تم حفظ صفحة من نحن!",
    storyImage: "صورة القصة",
    storySectionImage: "صورة قسم القصة",
    storyImageHint: "إذا تُرك فارغاً، سيُعرض الرمز التعبيري أدناه بدلاً منه.",
    groups: {
      header: "رأس الصفحة",
      story: "قسم القصة",
      values: "قسم القيم",
      process: "قسم العملية",
    },
    storyEmojiHint: "رمز القصة (يُعرض عند عدم وجود صورة)",
    valueIcon: "أيقونة القيمة {n}",
    valueTitleArabic: "عنوان القيمة {n} (عربي)",
    valueTitleEnglish: "عنوان القيمة {n} (إنجليزي)",
    valueTextArabic: "نص القيمة {n} (عربي)",
    valueTextEnglish: "نص القيمة {n} (إنجليزي)",
    storyTitleArabic: "عنوان القصة (عربي)",
    storyTitleEnglish: "عنوان القصة (إنجليزي)",
    storyP1Arabic: "فقرة القصة 1 (عربي)",
    storyP1English: "فقرة القصة 1 (إنجليزي)",
    storyP2Arabic: "فقرة القصة 2 (عربي)",
    storyP2English: "فقرة القصة 2 (إنجليزي)",
    valuesTitleArabic: "عنوان القيم (عربي)",
    valuesTitleEnglish: "عنوان القيم (إنجليزي)",
    processTitleArabic: "عنوان العملية (عربي)",
    processTitleEnglish: "عنوان العملية (إنجليزي)",
    stepTitleArabic: "عنوان الخطوة {n} (عربي)",
    stepTitleEnglish: "عنوان الخطوة {n} (إنجليزي)",
    stepTextArabic: "نص الخطوة {n} (عربي)",
    stepTextEnglish: "نص الخطوة {n} (إنجليزي)",
  },
  blog: {
    title: "المدونة",
    subtitle: "إدارة محتوى صفحة المدونة والمقالات بالعربية والإنجليزية.",
    previewBlog: "معاينة المدونة",
    addPost: "+ إضافة مقال",
    saveBlog: "حفظ المدونة",
    loading: "جاري تحميل المدونة...",
    loadFailed: "فشل تحميل المدونة.",
    noPosts: "لا توجد مقالات بعد",
    addFirstPost: "إضافة أول مقال",
    deleteConfirm: "هل تريد حذف هذا المقال؟",
    errorSaving: "حدث خطأ أثناء حفظ المدونة",
    saved: "تم حفظ المدونة!",
    pageHeader: "رأس صفحة المدونة",
    postCoverImage: "صورة غلاف المقال",
    newPost: "مقال جديد",
  },
  settings: {
    title: "إعدادات الموقع",
    saveAll: "حفظ جميع التغييرات",
    loading: "جاري تحميل الإعدادات...",
    errorSaving: "حدث خطأ أثناء حفظ الإعدادات",
    saved: "تم حفظ الإعدادات!",
    groups: {
      contact: "واتساب والتواصل",
      hero: "قسم البطل",
      footer: "التذييل",
      admin: "كلمة مرور المسؤول",
    },
    whatsappOwner: "رقم واتساب المالك (مثال: 201092313486)",
    whatsappBranch: "رقم واتساب الفرع (مثال: 201092313486)",
    heroBadgeEnglish: "شارة البطل (إنجليزي)",
    heroBadgeArabic: "شارة البطل (عربي)",
    heroTitleEnglish: "عنوان البطل (إنجليزي)",
    heroTitleArabic: "عنوان البطل (عربي)",
    heroDescriptionEnglish: "وصف البطل (إنجليزي)",
    heroDescriptionArabic: "وصف البطل (عربي)",
    footerEmail: "البريد الإلكتروني في التذييل",
    footerPhone: "الهاتف في التذييل",
    footerAddressEnglish: "العنوان في التذييل (إنجليزي)",
    footerAddressArabic: "العنوان في التذييل (عربي)",
    adminPassword: "كلمة مرور المسؤول الجديدة (اتركها فارغة للإبقاء على الحالية)",
    passwordPlaceholder: "اتركها فارغة للإبقاء على كلمة المرور الحالية",
    infoTitle: "ما يمكنك التحكم فيه هنا",
    infoText:
      "أرقام واتساب، نص البطل في الصفحة الرئيسية، بيانات التواصل في التذييل، وكلمة مرور المسؤول. التغييرات تُطبَّق على الموقع مباشرة بعد الحفظ.",
  },
  imagePicker: {
    defaultLabel: "صورة",
    selectedImage: "الصورة المختارة",
    noImageSelected: "لم يتم اختيار صورة",
    imageUrl: "رابط الصورة",
    uploading: "جاري الرفع...",
    uploadNew: "رفع صورة جديدة",
    searchGallery: "بحث في المعرض...",
    loadingGallery: "جاري تحميل المعرض...",
    noImagesFound: "لم يُعثر على صور.",
    uploadFailed: "فشل رفع الصورة",
  },
  categories: {
    "natural-honey": "عسل النحل الطبيعي",
    sidr: "عسل السدر",
    "bee-products": "منتجات النحل",
    "mixed-honey": "أعسال مختلطة",
    formulations: "التركيبات العلاجية",
    "vip-formulations": "تركيبات VIP",
    "natural-oils": "الزيوت الطبيعية والمنتجات الريفية",
    dates: "التمور",
  },
  productKind: {
    standard: "عادي",
    custom: "خلطة مخصصة",
    announcement: "قريباً",
  },
  productUnit: {
    fixed: "سعر ثابت",
    perGram: "بالجرام",
  },
} as const;

export function orderStatusLabel(status: string) {
  return (
    adminLabels.orderStatus[status as keyof typeof adminLabels.orderStatus] ??
    status
  );
}

export function partnershipStatusLabel(status: string) {
  return (
    adminLabels.partnershipStatus[
      status as keyof typeof adminLabels.partnershipStatus
    ] ?? status
  );
}

export function categoryLabel(category: string) {
  return (
    adminLabels.categories[category as keyof typeof adminLabels.categories] ??
    category
  );
}

export function itemCountLabel(count: number) {
  return count === 1 ? "عنصر واحد" : `${count} عناصر`;
}

export function formatAdminDate(date: string | Date) {
  return new Date(date).toLocaleDateString("ar-EG", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
}
